package cn.lonsun.staticcenter.exproject.tgq;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 *
 */
@WebService(name = "WebInter2016Soap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
        ObjectFactory.class
})
public interface WebInter2016Soap {

    /**
     * 取组配分类的接口,返回Json
     *
     * @param unit
     * @param xxflCode
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetColumnJson", action = "http://tempuri.org/GetColumnJson")
    @WebResult(name = "GetColumnJsonResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetColumnJson", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetColumnJson")
    @ResponseWrapper(localName = "GetColumnJsonResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetColumnJsonResponse")
    public String getColumnJson(
            @WebParam(name = "xxfl_code", targetNamespace = "http://tempuri.org/")
                    String xxflCode,
            @WebParam(name = "unit", targetNamespace = "http://tempuri.org/")
                    String unit);

    /**
     * 取主题分类的接口,返回Json
     *
     * @param unit
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetSubjectJson", action = "http://tempuri.org/GetSubjectJson")
    @WebResult(name = "GetSubjectJsonResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetSubjectJson", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetSubjectJson")
    @ResponseWrapper(localName = "GetSubjectJsonResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetSubjectJsonResponse")
    public String getSubjectJson(
            @WebParam(name = "unit", targetNamespace = "http://tempuri.org/")
                    String unit);

}
