
package cn.lonsun.staticcenter.exproject.lixin;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "IPortalService", targetNamespace = "http://services.ws.iflytek.com", wsdlLocation = "http://60.174.83.212/app-net-ws/services/IPortalService?wsdl")
public class IPortalService
    extends Service
{

    private final static URL IPORTALSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(IPortalService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = IPortalService.class.getResource(".");
            url = new URL(baseUrl, "http://60.174.83.212/app-net-ws/services/IPortalService?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://60.174.83.212/app-net-ws/services/IPortalService?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        IPORTALSERVICE_WSDL_LOCATION = url;
    }

    public IPortalService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IPortalService() {
        super(IPORTALSERVICE_WSDL_LOCATION, new QName("http://services.ws.iflytek.com", "IPortalService"));
    }

    /**
     * 
     * @return
     *     returns IPortalServicePortType
     */
    @WebEndpoint(name = "IPortalServiceHttpPort")
    public IPortalServicePortType getIPortalServiceHttpPort() {
        return super.getPort(new QName("http://services.ws.iflytek.com", "IPortalServiceHttpPort"), IPortalServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IPortalServicePortType
     */
    @WebEndpoint(name = "IPortalServiceHttpPort")
    public IPortalServicePortType getIPortalServiceHttpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://services.ws.iflytek.com", "IPortalServiceHttpPort"), IPortalServicePortType.class, features);
    }

}
